class CitationInserter:
    """
    Inserts inline citations into generated answers.

    Responsibilities

    • Insert inline citation markers
    • Preserve answer readability
    • Never invent citation ids

    Future responsibilities

    • Sentence-level attribution
    • Multi-source citations
    • Confidence-aware citations
    • Automatic citation placement
    """

    def insert(
        self,
        answer: str,
        sources: list[dict],
    ) -> dict:
        """
        Insert inline citations into an answer.

        Parameters
        ----------
        answer:
            Final answer generated by the LLM.

        sources:
            Retrieved source metadata.

        Returns
        -------
        {
            "answer": "... [1]",
            "citations": ["[1]"]
        }
        """

        if not sources:

            return {
                "answer": answer,
                "citations": [],
            }

        citation = "[1]"

        updated_answer = answer.rstrip()

        if citation not in updated_answer:

            if updated_answer.endswith("."):

                updated_answer = (
                    f"{updated_answer} {citation}"
                )

            else:

                updated_answer = (
                    f"{updated_answer}. {citation}"
                )

        return {
            "answer": updated_answer,
            "citations": [citation],
        }


citation_inserter = CitationInserter()