MEMORY_RULES = {
    "preferences": [
        "favorite",
        "prefer",
        "like",
        "love",
        "hate",
        "usually",
    ],
    "career": [
        "job",
        "career",
        "interview",
        "work",
        "engineer",
        "developer",
    ],
    "education": [
        "college",
        "university",
        "degree",
        "mca",
        "bachelor",
        "student",
    ],
    "skills": [
        "python",
        "sql",
        "fastapi",
        "docker",
        "react",
        "machine learning",
        "data science",
    ],
    "projects": [
        "project",
        "repository",
        "github",
        "application",
        "rag",
        "agent",
    ],
    "location": [
        "live",
        "city",
        "country",
        "bangalore",
        "hyderabad",
        "gurgaon",
        "india",
    ],
}