def test_self_query_filters_are_attached_to_strategy():
    ...

def test_self_query_semantic_query_is_used_by_strategy():
    ...

def test_plain_query_has_empty_filters():
    ...

def test_multiple_self_query_filters_are_preserved():
    ...

def test_planner_does_not_mutate_original_query():
    ...

def test_existing_strategy_flags_are_preserved():
    ...
    
